unbind C-b

set -g prefix C-a
set -g base-index 1
set -sg repeat-time 200
set -sg escape-time 10

setw -g pane-base-index 1
setw -g mode-keys vi

set -g default-terminal "tmux-256color"
set -as terminal-overrides ",*:Tc"
set -g history-limit 50000
set -g renumber-windows on
set -g allow-rename off
set -g focus-events on

bind r source-file ~/.tmux.conf \; display "Reloaded!"
bind C-a send-prefix
bind - split-window -v -c "#{pane_current_path}"
bind _ split-window -h -c "#{pane_current_path}"
bind m set -g mouse \; display "Mouse: #{?mouse,ON,OFF}"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind < swap-pane -U
bind > swap-pane -D

bind -r H resize-pane -L 2
bind -r J resize-pane -D 2
bind -r K resize-pane -U 2
bind -r L resize-pane -R 2

bind C-l next-window
bind C-h previous-window
bind Tab last-window

# copy mode
unbind [
unbind p
bind Enter copy-mode

bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi C-v send -X rectangle-toggle
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "xclip -i -selection clipboard"
bind -T copy-mode-vi Escape send -X cancel
bind -T copy-mode-vi H send -X start-of-line
bind -T copy-mode-vi L send -X end-of-line

set -g status-bg cyan

# buffers
bind b list-buffers
bind p paste-buffer
bind P choose-buffer
